pool:
  vmImage: 'ubuntu-latest'

trigger:
- refs/tags/*

steps:
- task: ArduinoCliInstall@1
  inputs:
    version: '0.9.0'

- task: ArduinoCliCoreUpdateIndex@0

- task: ArduinoCliCoreInstall@0
  inputs:
    core: 'arduino:avr'

- task: ArduinoCliLibdateIndex@0

- task: ArduinoCliLibInstall@0
  inputs:
    lib: 'OneWire@2.3.5'

- task: ArduinoCliLibInstall@0
  inputs:
    lib: 'DallasTemperature@3.8.0'

- task: ArduinoCliLibInstall@0
  inputs:
    lib: 'DHT sensor library@1.3.8'

- task: ArduinoCliLibInstall@0
  inputs:
    lib: 'CmdParser@1.6.0'

- task: ArduinoCliLibInstall@0
  inputs:
    lib: 'Adafruit Motor Shield library@1.0.1'

- task: ArduinoCliLibInstall@0
  inputs:
    lib: 'SparkFun APDS9960 RGB and Gesture Sensor@1.4.2'

- task: ArduinoCliLibInstall@0
  inputs:
    lib: 'SparkFun CCS811 Arduino Library@2.0.1'

- task: ArduinoCliBuild@0
  inputs:
    fqbn: 'arduino:avr:uno'
    sketchDir: '$(System.DefaultWorkingDirectory)/Main/'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/Main/build/arduino.avr.uno/'
    Contents: '*.hex'
    TargetFolder: '$(build.artifactstagingdirectory)/arduinoserial'
    CleanTargetFolder: true
    flattenFolders: true

- task: CmdLine@2
  displayName: 'Rename .hex files'
  inputs:
    script: |
      mv $(build.artifactstagingdirectory)/arduinoserial/Main.ino.hex $(build.artifactstagingdirectory)/arduinoserial/Main.ino.arduino.avr.uno.hex
      mv $(build.artifactstagingdirectory)/arduinoserial/Main.ino.with_bootloader.hex $(build.artifactstagingdirectory)/arduinoserial/Main.ino.arduino.avr.uno.with_bootloader.hex

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactstagingdirectory)/arduinoserial'
    artifact: 'ArduinoSerial-Firmware'
    publishLocation: 'pipeline'